version: '3'

services:
  mysql-block:
    restart: always
    container_name: mysql-block
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Ktjyfhlj2002
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Ktjyfhlj2002--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  web:
    restart: always
    build:
      context: article-server
      dockerfile: Dockerfile
    image: sr-rest-dev
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - '8089:8089'
    depends_on:
      - mysql-block

  front:
    restart: always
    container_name: front
    build: ./article-client
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - web